### ISSUE TITLE
Add "year" when using the function "Move survey from one route to another"

### ISSUE THREAD

**Issue by ekol-ali** [Lund-University-Biodiversity-data/intranet-ekol#2]
I just successfully moved survey data from one Fixed route to another. The survey data was recorded for 20F7**H** in 2020, but we yesterday found out that it should have been the route 20F7**C**.

After adding the activityID on the Intranet function, I got the correct survey up, which could be seen from the route code. However, it would have been nice to also get the YEAR of the survey to be changed, as another little check that I was really dealing with the intended route.

**Comment by mathieuLU** [comment]
fixed with commit https://github.com/Lund-University-Biodiversity-data/intranet-ekol/commit/d9bce23a6d0571ea6d5c6d8a16f2f83983af7e1b

![Screenshot from 2022-02-22 11-09-34](https://user-images.githubusercontent.com/50901365/155110867-fbab9d8f-5d94-4cc7-9480-bba81912606d.png)


to be checked and closed if ok

**Comment by ekol-ali** [comment]
Works nicely as far as I can see!
